# This is a basic workflow to help you get started with Actions

name: Patch Register

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  patch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Outputs a status message
      - name: Status message
        run: echo Deleting LMT Register!

      # Runs a set of commands using the runners shell
      - name: Delete the LMT register directory
        run: git rm -r dist/lmt

      # Outputs a status message
      - name: Status message
        run: echo Commit LMT Register deletion!

      # Runs a set of commands using the runners shell
      - name: Commit changes to repo
        run: git commit -m "Deleted LMT Register"
